site_name: Open Prices

nav:
  - Home: index.md
  - Dictionnaire des données: data_dictionary.md
  - Contexte métier détaillé: detailed_business_context.md
  - Organisation du projet: project_organization.md

theme:
  name: material
