site_name: Open Prices

nav:
  - Accueil: index.md
  - Dictionnaire des données: dictionnaire_donnees.md
  - Contexte métier détaillé: contexte_metier_detaille.md
  - Organisation du projet: organisation_projet.md
  - Remarques: remarques.md

theme:
  name: material

extra_javascript:
  - js/gtm.js
  - js/consent.js

extra:
  head:
    - |
      <!-- Google Tag Manager (noscript) -->
      <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MS6XBJGP"
        height="0" width="0" style="display:none;visibility:hidden"></iframe>
      </noscript>